---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-rtsp-2
  labels:
    app: virtual-rtsp-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-rtsp-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: virtual-rtsp-2
    spec:
      containers:
      - name: virtual-rtsp-2
        image: docker.io/kerberos/virtual-rtsp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8554
        env:
        - name: SOURCE_URL
          value: "https://www.tdhome.tw/streams/2-roundabout.mp4"
        livenessProbe:
          tcpSocket:
            port: 8554
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8554
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          privileged: false
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /tmp
          name: empty-dir
      volumes:
      - name: empty-dir
        emptyDir:
          sizeLimit: 1Gi
status: {}
